export const gallery = [
  {
    nama: "Bunga Aster",
    url: "https://drive.google.com/uc?export=view&id=1WHRp7_pCl3kTJPTAw8r530FPmRmLS0mF",
    kategori: "Nature",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Bunga Merah",
    url: "https://drive.google.com/uc?export=view&id=1M2oIza_iHlFeIO56GNZYiDQIKXdFXQBg",
    kategori: "Nature",
    desc: "Warnanya cantik kaya yang moto",
  },
  {
    nama: "Airplane View",
    url: "https://i.pinimg.com/564x/16/e7/b7/16e7b7c5efa3f4360205723f18004921.jpg",
    kategori: "Travel",
    desc: "Siap keliling dunia~",
  },
  {
    nama: "Hadi",
    url: "https://drive.google.com/uc?export=view&id=18K2MTchPXrxZTegBm6dBBEn1VU83FPrN",
    kategori: "Artist",
    desc: "Liboran",
  },
  {
    nama: "Jaehyun's Clothes",
    url: "https://i.pinimg.com/564x/42/2b/c0/422bc0e16f8dcef3c79c71ea0cfe84f8.jpg",
    kategori: "Fashion",
    desc: "Orang ganteng mah pake apa aja cakep",
  },
  {
    nama: "Brown Outfit",
    url: "https://i.pinimg.com/564x/24/3e/7e/243e7ec90fa90b9c4b76c217cd086186.jpg",
    kategori: "Fashion",
    desc: "Mau kemana yaa hari ini..",
  },
  {
    nama: "Monokrom",
    url: "https://i.pinimg.com/564x/57/77/a4/5777a453e5817cc5883b5ea08b9cd407.jpg",
    kategori: "Abstrak",
    desc: "Just an abstrack object",
  },
  {
    nama: "Hofif",
    url: "https://drive.google.com/uc?export=view&id=1d6TzU9Us3S6DsJNvkCOcay7SKrINLgbU",
    kategori: "Artist",
    desc: "Pura-pura candid dulu",
  },
  {
    nama: "Grey",
    url: "https://i.pinimg.com/564x/ed/3c/d8/ed3cd8ca8089507f2eda31882c41808d.jpg",
    kategori: "Abstrak",
    desc: "My current lockscreen wallpaper",
  },
  {
    nama: "Ball",
    url: "https://i.pinimg.com/564x/98/6c/81/986c810153214fcc52f11e0570157575.jpg",
    kategori: "Sport",
    desc: "I believe I can fly",
  },
  {
    nama: "Inez",
    url: "https://drive.google.com/uc?export=view&id=1r-Xy2W3g3M5iesgev25utgIxjkYljmbG",
    kategori: "Artist",
    desc: "Jangan lupa healing besti",
  },
  {
    nama: "Basketball",
    url: "https://i.pinimg.com/564x/6f/2c/5a/6f2c5a8f5b4479e5e5b4be9d927e4885.jpg",
    kategori: "Sport",
    desc: "Estetik juga yah potonya",
  },
  {
    nama: "Jaehyun Painting",
    url: "https://i.pinimg.com/564x/13/44/eb/1344eba6fa659c97f04cce5705a4dd22.jpg",
    kategori: "Art",
    desc: "Lukisan aja cakep apalagi aslinya",
  },
  {
    nama: "Aesthetic Art",
    url: "https://i.pinimg.com/564x/ec/27/1e/ec271ee185c6e56eac195853504e2861.jpg",
    kategori: "Art",
    desc: "Just a random pict",
  },
  {
    nama: "Spaghetti",
    url: "https://drive.google.com/uc?export=view&id=1J1glleiWgBuKbv_8dM58IAH05rdh4Nwu",
    kategori: "Food & Drink",
    desc: "Masakan ala ala for dinner",
  },
  {
    nama: "Nabilla",
    url: "https://drive.google.com/uc?export=view&id=1DHo88-fVm0Qq4iq6kqYI5UtcL2ENYsU7",
    kategori: "Artist",
    desc: "Nungguin kamu lama banget:)",
  },
  {
    nama: "Lunch",
    url: "https://drive.google.com/uc?export=view&id=1t70uNRkNUPx9PC0FTuReQ3YLTTrmzfnD",
    kategori: "Food & Drink",
    desc: "PAP dulu",
  },
  {
    nama: "kota A",
    url: "https://drive.google.com/uc?export=view&id=1UUbFFkSJTBXZMpoCpnBzHE3-4EEOsCOo",
    kategori: "Cities",
    desc: "Kabut ya say",
  },
  {
    nama: "Rafiq",
    url: "https://drive.google.com/uc?export=view&id=1GMRzbfaASLsDRbTMJWvZO1GWCOND-VxB",
    kategori: "Artist",
    desc: "Minal a'idzin wal faidzin",
  },
  {
    nama: "Night View",
    url: "https://drive.google.com/uc?export=view&id=1NwkH-RtVYdCHweFeBobKxafk-qppJvxk",
    kategori: "Cities",
    desc: "Such a wonderful night with a wonderful person",
  },
  {
    nama: "Kucing Oren ",
    url: "https://i.pinimg.com/564x/d1/d8/3e/d1d83e26ecda8b3eda4a479e28dbf6f4.jpg",
    kategori: "Animals",
    desc: "Cubingitttt",
  },
  {
    nama: "Putri",
    url: "https://drive.google.com/uc?export=view&id=1uX2uCMDxFI4vLxh_WWUvtC6dp1ci7m4c",
    kategori: "Artist",
    desc: "Beaches",
  },
  {
    nama: "Kucing Oren ",
    url: "https://drive.google.com/uc?export=view&id=1m6CT-7AzN52hCYdttVpsq9kw-LNxQu7W",
    kategori: "Animals",
    desc: "Harus nurut sama majikan",
  },
  {
    nama: "Rizka",
    url: "https://drive.google.com/uc?export=view&id=1scfCC3mnf8DxFP-_ovgnU0n8eG2rtzw-",
    kategori: "Artist",
    desc: "Jangan lupa minum",
  },
  {
    nama: "Strawberry Squash",
    url: "https://drive.google.com/uc?export=view&id=1hfIWRKRHfsdx6QMN9CZBs24ZYRUkL-Qe",
    kategori: "Food & Drink",
    desc: "Ga ngerti fungsinya daun apaan:)",
  },
  {
    nama: "Kucing Galak",
    url: "https://drive.google.com/uc?export=view&id=1XJeICVYQDYrokNk6YX8JU9Y4xHPI4um9",
    kategori: "Animals",
    desc: "Nyantai dong meng",
  },
  {
    nama: "Antony",
    url: "https://drive.google.com/uc?export=view&id=1fiduiLQyc2RfGyc8_ewfZ50YhAbte58r",
    kategori: "Artist",
    desc: "Jangan lupa pake masker teman",
  },
  {
    nama: "Gedung Tinggi",
    url: "https://drive.google.com/uc?export=view&id=1WlEuliPDBYtFe1U8wKjifPpVSUFitvYe",
    kategori: "Cities",
    desc: "Setinggi harapan orang tua",
  },
  {
    nama: "Senja",
    url: "https://drive.google.com/uc?export=view&id=19MTysh9ydiit7v8wZZE453SFSn_pDEb-",
    kategori: "Nature",
    desc: "Dunia dikala senja teduh pelita",
  },
  {
    nama: "Mirza",
    url: "https://drive.google.com/uc?export=view&id=1onF1cnojbGkrClmW9NNMAZ69G28N-aNz",
    kategori: "Artist",
    desc: "Melirik kamu dan dia :(",
  },
  {
    nama: "Gunung",
    url: "https://drive.google.com/uc?export=view&id=1TuZ5vH8qTQ513I-cU3_wgt9PCAsvUMBE",
    kategori: "Nature",
    desc: "Muncak time",
  },
  {
    nama: "Pantai",
    url: "https://drive.google.com/uc?export=view&id=1C_kTIi5DVQQcVlwdzZJWTxruqwqkaV5E",
    kategori: "Nature",
    desc: "Bersih gini kan enak yaa",
  },
  {
    nama: "Langit Sore",
    url: "https://drive.google.com/uc?export=view&id=1QUTmRfFfZWsWp1l3k8-xYdPHdjhu516F",
    kategori: "Nature",
    desc: "Sebab kau terlalu indah dari sekedar kata",
  },
  {
    nama: "Pepohonan",
    url: "https://drive.google.com/uc?export=view&id=1iAnfvgqLLS062KgvUXcDV68aMDNNV7RM",
    kategori: "Nature",
    desc: "Fresh air",
  },
  {
    nama: "Tiara",
    url: "https://drive.google.com/uc?export=view&id=1UarVgvWa2qoxWlOWB-TQDpCoo2yzqQzz",
    kategori: "Artist",
    desc: "Jalan-jalan yu",
  },
  {
    nama: "Taman",
    url: "https://drive.google.com/uc?export=view&id=1UPLR6zmugIEacoXsadhN1FcJd-TAkpcC",
    kategori: "Nature",
    desc: "Nice view kann",
  },
  {
    nama: "Hutan",
    url: "https://drive.google.com/uc?export=view&id=1TfrC1g_L03373V7ylpnTEGyDPrFRnHZs",
    kategori: "Nature",
    desc: "Udah kaya foto pinterest yakan",
  },
  {
    nama: "Bukit",
    url: "https://drive.google.com/uc?export=view&id=1Tu3wRKK5hGqtS1VuqceyqJt3WvTw0YW_",
    kategori: "Nature",
    desc: "Kita pernah lama bersama, suatu titik di bukit ini adalah kita",
  },
  {
    nama: "Sawah",
    url: "https://drive.google.com/uc?export=view&id=1SatwRAzgXFnO5_7JJw76vd9pn6lMdsOh",
    kategori: "Nature",
    desc: "Pulang kampung vibe",
  },
  {
    nama: "Langit",
    url: "https://drive.google.com/uc?export=view&id=1SXJfnJpq8ekoRym8Mzt2yXnsWpZ-_49z",
    kategori: "Nature",
    desc: "Mungkin tak slalu biru, namun bersamamu langitku tak lagi sendu",
  },
  {
    nama: "Sore",
    url: "https://drive.google.com/uc?export=view&id=1WvWFnNB4dhuSgOOuIC9idRkDLYcubbpW",
    kategori: "Nature",
    desc: "Penikmat senja bgt nih",
  },
  {
    nama: "Aesthetic City",
    url: "https://drive.google.com/uc?export=view&id=1Ke2I441-LDt_Z7tH7EBZVz6ShjTEjnDY",
    kategori: "Cities",
    desc: "Pemandangan dari jendela kantor di sore hari",
  },
  {
    nama: "Sunday Morning",
    url: "https://drive.google.com/uc?export=view&id=1_ine3Qlv84jHaY9VvjsdSOyAWl7LYRQK",
    kategori: "Sport",
    desc: "Jogging with bestiess",
  },
  {
    nama: "OOTD",
    url: "https://drive.google.com/uc?export=view&id=1a_W0SA8GqCbNTuoXvfdyUjcdgC7iLJk5",
    kategori: "Fashion",
    desc: "Neww DocMart match the outfit",
  },
  {
    nama: "Concert Day!",
    url: "https://drive.google.com/uc?export=view&id=1geWO9dbE3iL9rmjmXikhHg2JiuFB-yth",
    kategori: "Abstrak",
    desc: "Fangirling timee",
  },
  {
    nama: "Aisha",
    url: "https://drive.google.com/uc?export=view&id=1Z37NN6XELjgtVbUGLoTpQ3SakwO7lrbg",
    kategori: "Artist",
    desc: "Jangan lupa tersenyum",
  },
  {
    nama: "Still Healthy",
    url: "https://drive.google.com/uc?export=view&id=1K6Fnn4w6RbuctCm_IWMhVxJuX_9jU33n",
    kategori: "Sport",
    desc: "OMW to my dream body",
  },
  {
    nama: "Hairdo",
    url: "https://drive.google.com/uc?export=view&id=11S2QcgEbTvkRLQ5lhN-CgGjKuyYi7X5Y",
    kategori: "Fashion",
    desc: "Luvv my new hair",
  },
  {
    nama: "Rumit",
    url: "https://drive.google.com/uc?export=view&id=1z2oYnKp2hgLqD9r29rGEFCYzOSvxAMJj",
    kategori: "Abstrak",
    desc: "Ruwet kaya tugas kuliah",
  },
  {
    nama: "Koala",
    url: "https://drive.google.com/uc?export=view&id=1JjHHIXp1-BoMrVP_3-LnOc_y7GdtsYgs",
    kategori: "Animals",
    desc: "Not koala but idk what is it?",
  },
  {
    nama: "Simple Nail",
    url: "https://drive.google.com/uc?export=view&id=14A-v0wnyco3BsNJ2qx4rUslfdnQ2jNur",
    kategori: "Fashion",
    desc: "Neww nail art",
  },
  {
    nama: "Aulia",
    url: "https://drive.google.com/uc?export=view&id=1frn1A8nmCd2-lErNjhjo1r5YxxGnBBm-",
    kategori: "Artist",
    desc: "Ngafe dulu yuk",
  },
  {
    nama: "Jalanan sore",
    url: "https://drive.google.com/uc?export=view&id=1xdIBxxnIpB5bBCdbhKPjlk12Jkmt4kOx",
    kategori: "Travel",
    desc: "Muacettt is always",
  },
  {
    nama: "Stasiun",
    url: "https://drive.google.com/uc?export=view&id=1_kJrAPUYb0wapzcd-lyiR9rMAyyTVWWO",
    kategori: "Travel",
    desc: "OTW kemana yaa",
  },
  {
    nama: "Gunung Kabut",
    url: "https://drive.google.com/uc?export=view&id=14Dx9way4Zbo87AEiForpZWm28h3S3tVS",
    kategori: "Nature",
    desc: "Say Masya Allah",
  },
  {
    nama: "Evaa",
    url: "https://drive.google.com/uc?export=view&id=1IcTAQ7HNzEPxhk-kihmOdqxeGu5fJ3lL",
    kategori: "Artist",
    desc: "Jung Fakhriyyatum Muslimah (Istrinya Jaehyun) ",
  },
  {
    nama: "Airplane View",
    url: "https://drive.google.com/uc?export=view&id=1NUPqeUhMdiqNbkHenLXCdJezVXSFvib8",
    kategori: "Travel",
    desc: "Healing dulu yang baru kelar UAS",
  },
];
